version: '3'
services:
  mysql_container:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"

  ski_app:
    container_name: stationSki
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=emnamasmoudi/backend
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysql_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container/stationSki?createDatabaseIfNoExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root







