version: '3'
services:
  mysql_container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"

  ski_app:
    image: emnamasmoudi/5twin5-g1-skistation
    ports:
      - "8089:8089"
    depends_on:
      - mysql_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container/stationSki?createDatabaseIfNoExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root







